name: Reusable test matrix generation

on:
  workflow_call:
    inputs:
      intel_drivers_image:
        type: string
        required: false
        default: "ghcr.io/intel/llvm/ubuntu2204_intel_drivers:latest"
      amdgpu_image:
        type: string
        required: false
        default: "ghcr.io/intel/llvm/ubuntu2204_build:latest"
      cuda_image:
        type: string
        required: false
        default: "ghcr.io/intel/llvm/ubuntu2204_build:latest"
      lts_config:
        type: string
        required: true
        default: ""
      cts_config:
        type: string
        required: false
        default: ""
      uniq:
        description: Unique string to name dynamic runners in AWS
        type: string
        required: false
        default: ${{ github.run_id }}-${{ github.run_attempt }}
      ref:
        description: "Commit to use for checkout or github.sha by default"
        type: string
        required: false
        default: ${{ github.sha }}
      drivers_update_needed:
        description: "True indicates that dependencies.json has changed"
        type: string
        required: false
        default: false
    outputs:
      lts_lx_matrix:
        description: "Linux LTS"
        value: ${{ jobs.test_matrix.outputs.lts_lx_matrix }}
      lts_wn_matrix:
        description: "Windows LTS"
        value: ${{ jobs.test_matrix.outputs.lts_wn_matrix }}
      cts_matrix:
        description: "SYCL CTS"
        value: ${{ jobs.test_matrix.outputs.cts_matrix }}
      lts_aws_matrix:
        description: "Linux AWS"
        value: ${{ jobs.test_matrix.outputs.lts_aws_matrix }}
jobs:
  test_matrix:
    name: Generate Test Matrix
    # Github's ubuntu-* runner are slow to allocate. Use our CUDA runner since
    # we don't use it for anything right now.
    runs-on: [Linux, build]
    outputs:
      lts_lx_matrix: ${{ steps.work.outputs.lts_lx_matrix }}
      lts_wn_matrix: ${{ steps.work.outputs.lts_wn_matrix }}
      cts_matrix: ${{ steps.work.outputs.cts_matrix }}
      lts_aws_matrix: ${{ steps.work.outputs.lts_aws_matrix }}
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.ref }}
        sparse-checkout: |
          devops/scripts/generate_test_matrix.js
          devops/test_configs.json
    - id: work
      uses: actions/github-script@v6
      name: Generate matrix
      env:
        GHA_INPUTS: ${{ toJSON(inputs) }}
      with:
        script: |
          const script = require('./devops/generate_test_matrix.js');
          script({core, process});
